
package br.com.caelum.cliente.testejboss;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ConsultaDeLivrosBean", targetNamespace = "http://ws.loja.caelum.com.br/")
public interface ConsultaDeLivrosBean {


    /**
     * 
     * @param nome
     * @return
     *     returns java.util.List<br.com.caelum.cliente.testejboss.Livro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscaLivro", targetNamespace = "http://ws.loja.caelum.com.br/", className = "br.com.caelum.cliente.testejboss.BuscaLivro")
    @ResponseWrapper(localName = "buscaLivroResponse", targetNamespace = "http://ws.loja.caelum.com.br/", className = "br.com.caelum.cliente.testejboss.BuscaLivroResponse")
    public List<Livro> buscaLivro(
        @WebParam(name = "nome", targetNamespace = "")
        String nome);

}
