
package br.com.caelum.cliente.testejboss;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ConsultaDeLivrosBeanService", targetNamespace = "http://ws.loja.caelum.com.br/", wsdlLocation = "http://localhost:8080/ConsultaDeLivrosBeanService/ConsultaDeLivrosBean?wsdl")
public class ConsultaDeLivrosBeanService
    extends Service
{

    private final static URL CONSULTADELIVROSBEANSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ConsultaDeLivrosBeanService/ConsultaDeLivrosBean?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CONSULTADELIVROSBEANSERVICE_WSDL_LOCATION = url;
    }

    public ConsultaDeLivrosBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaDeLivrosBeanService() {
        super(CONSULTADELIVROSBEANSERVICE_WSDL_LOCATION, new QName("http://ws.loja.caelum.com.br/", "ConsultaDeLivrosBeanService"));
    }

    /**
     * 
     * @return
     *     returns ConsultaDeLivrosBean
     */
    @WebEndpoint(name = "ConsultaDeLivrosBeanPort")
    public ConsultaDeLivrosBean getConsultaDeLivrosBeanPort() {
        return (ConsultaDeLivrosBean)super.getPort(new QName("http://ws.loja.caelum.com.br/", "ConsultaDeLivrosBeanPort"), ConsultaDeLivrosBean.class);
    }

}
