
package br.com.caelum.cliente.testeisrael;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CalculadorDeParcela", targetNamespace = "http://webservices.caelum.com.br/")
public interface CalculadorDeParcela {


    /**
     * 
     * @param qunatidade
     * @param valorTotal
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculaParcela", targetNamespace = "http://webservices.caelum.com.br/", className = "br.com.caelum.cliente.testeisrael.CalculaParcela")
    @ResponseWrapper(localName = "calculaParcelaResponse", targetNamespace = "http://webservices.caelum.com.br/", className = "br.com.caelum.cliente.testeisrael.CalculaParcelaResponse")
    public double calculaParcela(
        @WebParam(name = "valorTotal", targetNamespace = "")
        double valorTotal,
        @WebParam(name = "qunatidade", targetNamespace = "")
        int qunatidade);

}
